//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoppaClient.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NoppaClient.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Section xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;&gt;
        ///&lt;Paragraph&gt;
        ///Noppa client for Windows Phone 8.
        ///&lt;LineBreak/&gt;
        ///&lt;/Paragraph&gt;
        ///&lt;Paragraph&gt;
        ///Developed during the spring of 2013 as a project for the
        ///course &lt;Run FontStyle=&quot;Italic&quot;&gt;T-110.5130 Mobile Systems Programming&lt;/Run&gt; at 
        ///&lt;Hyperlink NavigateUri=&quot;http://www.aalto.fi/&quot; TargetName=&quot;_blank&quot;&gt;Aalto university&lt;/Hyperlink&gt; 
        ///by Aura Palmgren, Kari Palenius, Evans Mungai, Vesa Eloranta and Christoffer Ventus.
        ///&lt;/Paragraph&gt;
        ///&lt;/Section&gt;.
        /// </summary>
        public static string AboutTextXaml {
            get {
                return ResourceManager.GetString("AboutTextXaml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add course tile.
        /// </summary>
        public static string AddCourseTileLabel {
            get {
                return ResourceManager.GetString("AddCourseTileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add event.
        /// </summary>
        public static string AddToCalendarTitle {
            get {
                return ResourceManager.GetString("AddToCalendarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to noppa.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assignments.
        /// </summary>
        public static string AssignmentsTitle {
            get {
                return ResourceManager.GetString("AssignmentsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assessment.
        /// </summary>
        public static string CourseAssessmentTitle {
            get {
                return ResourceManager.GetString("CourseAssessmentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEFR level.
        /// </summary>
        public static string CourseCEFRLevelTitle {
            get {
                return ResourceManager.GetString("CourseCEFRLevelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to content.
        /// </summary>
        public static string CourseContentTitle {
            get {
                return ResourceManager.GetString("CourseContentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to credits.
        /// </summary>
        public static string CourseCreditsTitle {
            get {
                return ResourceManager.GetString("CourseCreditsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to details.
        /// </summary>
        public static string CourseDetailsTitle {
            get {
                return ResourceManager.GetString("CourseDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to grading scale.
        /// </summary>
        public static string CourseGradingScaleTitle {
            get {
                return ResourceManager.GetString("CourseGradingScaleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to instruction language.
        /// </summary>
        public static string CourseInstructionLanguageTitle {
            get {
                return ResourceManager.GetString("CourseInstructionLanguageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to learning outcomes.
        /// </summary>
        public static string CourseLearningOutcomesTitle {
            get {
                return ResourceManager.GetString("CourseLearningOutcomesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to level.
        /// </summary>
        public static string CourseLevelTitle {
            get {
                return ResourceManager.GetString("CourseLevelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to course name.
        /// </summary>
        public static string CourseNameTitle {
            get {
                return ResourceManager.GetString("CourseNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to office hours.
        /// </summary>
        public static string CourseOfficeHoursTitle {
            get {
                return ResourceManager.GetString("CourseOfficeHoursTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to prerequisites.
        /// </summary>
        public static string CoursePrerequisitesTitle {
            get {
                return ResourceManager.GetString("CoursePrerequisitesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to registration.
        /// </summary>
        public static string CourseRegistrationTitle {
            get {
                return ResourceManager.GetString("CourseRegistrationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to staff.
        /// </summary>
        public static string CourseStaffTitle {
            get {
                return ResourceManager.GetString("CourseStaffTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to status.
        /// </summary>
        public static string CourseStatusTitle {
            get {
                return ResourceManager.GetString("CourseStatusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to study material.
        /// </summary>
        public static string CourseStudyMaterialTitle {
            get {
                return ResourceManager.GetString("CourseStudyMaterialTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to substitutes.
        /// </summary>
        public static string CourseSubstitutesTitle {
            get {
                return ResourceManager.GetString("CourseSubstitutesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to teaching period.
        /// </summary>
        public static string CourseTeachingPeriodTitle {
            get {
                return ResourceManager.GetString("CourseTeachingPeriodTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to workload.
        /// </summary>
        public static string CourseWorkloadTitle {
            get {
                return ResourceManager.GetString("CourseWorkloadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string DepartmentCourseListTitle {
            get {
                return ResourceManager.GetString("DepartmentCourseListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to departments.
        /// </summary>
        public static string DepartmentsTitle {
            get {
                return ResourceManager.GetString("DepartmentsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string DepartmentTitle {
            get {
                return ResourceManager.GetString("DepartmentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to english.
        /// </summary>
        public static string EnglishLanguage {
            get {
                return ResourceManager.GetString("EnglishLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to casework.
        /// </summary>
        public static string EventCaseworkTitle {
            get {
                return ResourceManager.GetString("EventCaseworkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to course event.
        /// </summary>
        public static string EventCourseEventTitle {
            get {
                return ResourceManager.GetString("EventCourseEventTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to demonstration.
        /// </summary>
        public static string EventDemonstrationTitle {
            get {
                return ResourceManager.GetString("EventDemonstrationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exam.
        /// </summary>
        public static string EventExamTitle {
            get {
                return ResourceManager.GetString("EventExamTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to group studies.
        /// </summary>
        public static string EventGroupStudies {
            get {
                return ResourceManager.GetString("EventGroupStudies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hybrid studies.
        /// </summary>
        public static string EventHybridStudies {
            get {
                return ResourceManager.GetString("EventHybridStudies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to individual studies.
        /// </summary>
        public static string EventIndividualStudies {
            get {
                return ResourceManager.GetString("EventIndividualStudies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mid term exam.
        /// </summary>
        public static string EventMidTermExamTitle {
            get {
                return ResourceManager.GetString("EventMidTermExamTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to online studies.
        /// </summary>
        public static string EventOnlineStudies {
            get {
                return ResourceManager.GetString("EventOnlineStudies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to other.
        /// </summary>
        public static string EventOtherTitle {
            get {
                return ResourceManager.GetString("EventOtherTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seminar.
        /// </summary>
        public static string EventSeminarTitle {
            get {
                return ResourceManager.GetString("EventSeminarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to events.
        /// </summary>
        public static string EventsTitle {
            get {
                return ResourceManager.GetString("EventsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exercises.
        /// </summary>
        public static string ExercisesTitle {
            get {
                return ResourceManager.GetString("ExercisesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to suomi.
        /// </summary>
        public static string FinnishLanguage {
            get {
                return ResourceManager.GetString("FinnishLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to friday.
        /// </summary>
        public static string FridayTitle {
            get {
                return ResourceManager.GetString("FridayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to published.
        /// </summary>
        public static string GradePublishedTitle {
            get {
                return ResourceManager.GetString("GradePublishedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to results.
        /// </summary>
        public static string GradeResultsTitle {
            get {
                return ResourceManager.GetString("GradeResultsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to grade review.
        /// </summary>
        public static string GradeReviewTitle {
            get {
                return ResourceManager.GetString("GradeReviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to grade scale.
        /// </summary>
        public static string GradeScaleTitle {
            get {
                return ResourceManager.GetString("GradeScaleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to language.
        /// </summary>
        public static string LanguageTitle {
            get {
                return ResourceManager.GetString("LanguageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lectures.
        /// </summary>
        public static string LecturesTitle {
            get {
                return ResourceManager.GetString("LecturesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to monday.
        /// </summary>
        public static string MondayTitle {
            get {
                return ResourceManager.GetString("MondayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my courses.
        /// </summary>
        public static string MyCoursesTitle {
            get {
                return ResourceManager.GetString("MyCoursesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to news.
        /// </summary>
        public static string NewsTitle {
            get {
                return ResourceManager.GetString("NewsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no results, try again later.
        /// </summary>
        public static string NoDepartmentCoursesTitle {
            get {
                return ResourceManager.GetString("NoDepartmentCoursesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to noppa search.
        /// </summary>
        public static string NoppaSearchTitle {
            get {
                return ResourceManager.GetString("NoppaSearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no results.
        /// </summary>
        public static string NoSearchResultsTitle {
            get {
                return ResourceManager.GetString("NoSearchResultsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        public static string OrganizationTitle {
            get {
                return ResourceManager.GetString("OrganizationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to overview.
        /// </summary>
        public static string OverviewTitle {
            get {
                return ResourceManager.GetString("OverviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pin.
        /// </summary>
        public static string PinCourseTitle {
            get {
                return ResourceManager.GetString("PinCourseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove course tile.
        /// </summary>
        public static string RemoveCourseTileLabel {
            get {
                return ResourceManager.GetString("RemoveCourseTileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to results.
        /// </summary>
        public static string ResultsTitle {
            get {
                return ResourceManager.GetString("ResultsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Runtime Property Value.
        /// </summary>
        public static string SampleProperty {
            get {
                return ResourceManager.GetString("SampleProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to saturday.
        /// </summary>
        public static string SaturdayTitle {
            get {
                return ResourceManager.GetString("SaturdayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Section xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;&gt;
        ///&lt;Paragraph&gt;
        ///&lt;Run FontWeight=&quot;Bold&quot;&gt;search tips&lt;/Run&gt;
        ///&lt;/Paragraph&gt;
        ///&lt;Paragraph&gt;
        ///You can search by course name, part of the course name, course code or part of the course code.
        ///&lt;/Paragraph&gt;
        ///&lt;Paragraph&gt;
        ///&lt;Run FontWeight=&quot;Bold&quot;&gt;example searches&lt;/Run&gt;
        ///&lt;/Paragraph&gt;
        ///&lt;Paragraph&gt;&amp;#9679; TU-53.1145&lt;/Paragraph&gt;
        ///&lt;Paragraph&gt;&amp;#9679; TU-53.1&lt;/Paragraph&gt;
        ///&lt;Paragraph&gt;&amp;#9679; TU-53&lt;/Paragraph&gt;
        ///&lt;Paragraph&gt;&amp;#9679; Leadership in product develo [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SearchHintTextXaml {
            get {
                return ResourceManager.GetString("SearchHintTextXaml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course results for “{0}”.
        /// </summary>
        public static string SearchResultsPageTitle {
            get {
                return ResourceManager.GetString("SearchResultsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string SearchTitle {
            get {
                return ResourceManager.GetString("SearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by code.
        /// </summary>
        public static string SortByCodeTitle {
            get {
                return ResourceManager.GetString("SortByCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by unit.
        /// </summary>
        public static string SortByDepartmentTitle {
            get {
                return ResourceManager.GetString("SortByDepartmentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by name.
        /// </summary>
        public static string SortByNameTitle {
            get {
                return ResourceManager.GetString("SortByNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sunday.
        /// </summary>
        public static string SundayTitle {
            get {
                return ResourceManager.GetString("SundayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to svenska.
        /// </summary>
        public static string SwedishLanguage {
            get {
                return ResourceManager.GetString("SwedishLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thursday.
        /// </summary>
        public static string ThursdayTitle {
            get {
                return ResourceManager.GetString("ThursdayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tuesday.
        /// </summary>
        public static string TuesdayTitle {
            get {
                return ResourceManager.GetString("TuesdayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unpin.
        /// </summary>
        public static string UnpinCourseTitle {
            get {
                return ResourceManager.GetString("UnpinCourseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically update primary tile.
        /// </summary>
        public static string UpdateTileLocalSettings {
            get {
                return ResourceManager.GetString("UpdateTileLocalSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wednesday.
        /// </summary>
        public static string WednesdayTitle {
            get {
                return ResourceManager.GetString("WednesdayTitle", resourceCulture);
            }
        }
    }
}
